### ISSUE TITLE
How to not break selector specificity ?

### ISSUE THREAD

**Issue by sylvainpolletvillard** [RyanZim/postcss-simplify-selectors#1]
Replacing selectors with classnames change the selector specificity and may break intended priority overrides.

Example:

Input:
```html
<ul>
<li>should be green</li>
<li>should be red</li>
</ul>
```

```css
ul > li:first-child {
	background-color: green;
}

ul > li {
	background-color: red;
}
```

Output:

```html
<ul>
<li class="_a9c6b _55267">should be green</li> <--- becomes red
<li class="_55267">should be red</li>
</ul>
```

```css
._a9c6b {
	background-color: green;
}

._55267 {
	background-color: red;
}
```
